SSD-Mobilenet-v2 TensorRT Generation from Frozen Graph using UFF Parser
neuralet/neuralet pull request #113
Opened 2020-05-19 18:32 UTC by emma-w-dev

I have added a docker container to install required packages and run a script to generate a TensorRT Engine as I explained in #89 on Jetson Nano

2020-05-20 05:58 UTC, mhejrati commented
@JsonSadler do you mind reviewing this?

2020-05-21 04:42 UTC, JsonSadler commented
> @JsonSadler do you mind reviewing this?

Hi @mhejrati 
Sure.

2020-05-21 14:49 UTC, mhejrati requested changes

2020-05-21 14:49 UTC, mhejrati commented on training/tensorrt_generation/Dockerfile
> +# 1) build: docker build -f Dockerfile -t "neuralet/l4t-tensorrt-conversion" .
How about this?
neuralet/jetson-nano:tf-ssd-to-trt

2020-05-21 14:49 UTC, mhejrati commented on training/tensorrt_generation/build_engine.py
> +    if model == 'ssd_mobilenet_v1_coco':
What does this do?

2020-05-21 14:49 UTC, mhejrati commented on training/tensorrt_generation/build_engine.py
> +
docstring, please :)

2020-05-21 14:49 UTC, mhejrati commented on training/tensorrt_generation/config.ini
> +[MODEL]
Can we add documentation for each of these configs?

2020-05-21 21:17 UTC, emma-w-dev commented on training/tensorrt_generation/Dockerfile
> +# 1) build: docker build -f Dockerfile -t "neuralet/l4t-tensorrt-conversion" .
modified, thanks

2020-05-21 22:01 UTC, emma-w-dev commented on training/tensorrt_generation/build_engine.py
> +
added, thanks

2020-05-23 13:49 UTC, emma-w-dev commented on training/tensorrt_generation/build_engine.py
> +    if model == 'ssd_mobilenet_v1_coco':
This line removes a connection from image_tensor node to the Input node and this connection just exist on ssd-mobilenet-v1. Modified this `if` to not to check it by the model name as it's not relevant by just renaming it.

2020-05-23 13:50 UTC, emma-w-dev commented on training/tensorrt_generation/config.ini
> +[MODEL]
yes, I also added some sample configs.

2020-05-23 16:21 UTC, emma-w-dev commented
Hi, I modified the pr contents as bellow:
- Modularized the script to support both ssd-mobilenet-v1 and ssd-mobilenet-v2 models which are trained using any version of object detection api and in a way to be able to add support for ssd-inception soon.
- Added different sample config files for both v1 and v2 with documentations 
- Moved files into ssd subdirectoy
- Removed download_model script and added download path to config files and moved downloading part to the main script 
- Performed required Dockerfile and Readme modifications
@mhejrati @JsonSadler

2020-05-29 15:37 UTC, mhejrati approved these changes
Thanks for making the changes.

2020-05-29 15:37 UTC, merged