Statistics
neuralet/neuralet pull request #34
Opened 2020-04-13 19:37 UTC by alpha-carinae29

add a CSV logger that log detected objects (persons) information and violated social distancing incidents with user defined frequency into CSV files.
related to #19

2020-04-14 00:57 UTC, mhejrati commented
@mrn-mln @JsonSadler can you please provide feedback on this PR?

2020-04-14 16:18 UTC, mrn-mln requested changes
@alpha-carinae29 Thank you. I reviewed your PR and left some comments.

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +    """
Please capitalize the first letter of each sentence of the docstring.

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +    for key, value in object_item.items():
I suggest renaming "object_item" to "detected_object" or "detected_objects". Be careful using s after variables name if there is more than one object at the dictionary.

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +    object_dict = {}
For the sake of clearance rename it to object**s**_dict if there is more than one object

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +                    item = round(float(item), 4)
Add a TODO to this line. 
"TODO: Why some items types are float and others are np.float?"

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +
Please capitalize the first letter of each sentence of the docstring.
Change class docstring to this format:
"""
 Description.....

:param pr1: Description ...
:param pr2: Description ...
"""

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +            elif isinstance(value, np.float32):
"TODO: Why the type of values are different?"

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +                    item = round(float(item), 4)
I think it does work for both types
item = round(float(item, 4))
And If you want to check the instance type you can write something like this:
if (isinstance(item, float) and isinstance(item, npfloat32)): item = round(float(item, 4))

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +        """
Please capitalize the first letter of each sentence of the docstring.

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +            A 2-d numpy array where each row is the ids of the objects that violated the social distancing.
Returns:
        violating_objects: A 2-d numpy ...

2020-04-14 16:18 UTC, mrn-mln commented on applications/smart-distancing/libs/loggers/loggers.py
> +    """
Using the mentioned format for docstring

2020-04-14 17:17 UTC, alpha-carinae29 commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +    object_dict = {}
no it only contains one object information

2020-04-14 17:19 UTC, alpha-carinae29 commented on applications/smart-distancing/libs/loggers/csv_logger.py
> +
I change the docstring format to be consistent with the rest of the code base but I think it is better to choose the Google's style later.

2020-04-15 05:59 UTC, mhejrati approved these changes
Looks good, thanks @alpha-carinae29

2020-04-15 06:00 UTC, mhejrati commented
@alpha-carinae29 can you please resolve the conflicts and resubmit.

2020-04-16 14:16 UTC, alpha-carinae29 commented
@mhejrati I resolved conflicts

2020-04-16 14:48 UTC, merged